Algoritmo "EscolhaCor"

Var
   cor: caractere

Inicio
   escreva("Digite uma cor: ")
   leia(cor)
   escolha cor
   caso "VERDE"
      escreva("Preço: R$10,00")
   caso "AZUL"
      escreva("Preço: R$20,00")
   caso "AMARELO"
      escreva("Preço: R$30,00")
   caso "V"
      escreva("Preço: R$40,00")
   outrocaso
      escreva("Cor indisponível.")
   fimescolha


Fimalgoritmo