Algoritmo "Operacoes"

Var
num1, num2, soma, subt, mult, divi: real

Inicio
 escreva("Digite o primeiro número: ")
 leia(num1)
 escreva("Digite o segundo número: ")
 leia(num2)
 soma:= num1+num2
 subt:= num1-num2
 mult:= num1*num2
 divi:= num1/num2
 escreval("O resultado da soma é: ", soma)
 escreval("Subtração: ", subt)
 escreval("Multiplicação: ", mult)
 escreval("Divisão: ", divi)

Fimalgoritmo